CREATE TABLE "email_history" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"human_id" uuid NOT NULL,
	"email" varchar(255) NOT NULL,
	"effective_from" timestamp with time zone DEFAULT now() NOT NULL,
	"effective_to" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "activities" ADD COLUMN "created_by" uuid NOT NULL;--> statement-breakpoint
ALTER TABLE "email_history" ADD CONSTRAINT "email_history_human_id_humans_id_fk" FOREIGN KEY ("human_id") REFERENCES "public"."humans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "email_history_human_idx" ON "email_history" USING btree ("human_id");--> statement-breakpoint
CREATE INDEX "email_history_email_idx" ON "email_history" USING btree ("email");--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_created_by_humans_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."humans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE VIEW "public"."category_spending_for_analysis" AS (SELECT category, count(*) AS expense_count, round(sum(amount)::numeric / 100.0, 2) AS subtotal_dollars, round(sum(tip_amount)::numeric / 100.0, 2) AS total_tips_dollars, round(sum(amount + tip_amount)::numeric / 100.0, 2) AS total_dollars, round(avg(amount + tip_amount) / 100.0, 2) AS avg_expense_dollars, round(max(amount)::numeric / 100.0, 2) AS max_expense_dollars, round(min(amount)::numeric / 100.0, 2) AS min_expense_dollars FROM expenses e WHERE category IS NOT NULL GROUP BY category ORDER BY (round(sum(amount + tip_amount)::numeric / 100.0, 2)) DESC);--> statement-breakpoint
CREATE VIEW "public"."daily_spending_trend_for_analysis" AS (SELECT created_at::date AS expense_date, date_part('year'::text, created_at)::integer AS year, date_part('month'::text, created_at)::integer AS month, date_part('week'::text, created_at)::integer AS week, count(*) AS expense_count, round(sum(amount)::numeric / 100.0, 2) AS subtotal_dollars, round(sum(tip_amount)::numeric / 100.0, 2) AS total_tips_dollars, round(sum(amount + tip_amount)::numeric / 100.0, 2) AS daily_total_dollars, round(avg(amount + tip_amount) / 100.0, 2) AS avg_expense_dollars, count(DISTINCT paid_by) AS unique_payers FROM expenses e GROUP BY (created_at::date), (date_part('year'::text, created_at)), (date_part('month'::text, created_at)), (date_part('week'::text, created_at)) ORDER BY (created_at::date) DESC);--> statement-breakpoint
CREATE VIEW "public"."events_summary_for_analysis" AS (SELECT ev.id AS event_id, ev.title AS event_name, ev.type AS event_type, ev.status, ev.currency, ev.start_time::date AS start_date, ev.end_time::date AS end_date, ev.end_time - ev.start_time AS duration_days, count(DISTINCT e.id) AS total_expenses, round(sum(e.amount + e.tip_amount)::numeric / 100.0, 2) AS total_spending_dollars, round(avg(e.amount + e.tip_amount) / 100.0, 2) AS avg_expense_dollars, count(DISTINCT e.paid_by) AS unique_payers FROM events ev LEFT JOIN expenses e ON ev.id = e.event_id GROUP BY ev.id, ev.title, ev.type, ev.status, ev.currency, ev.start_time, ev.end_time ORDER BY ev.created_at DESC);--> statement-breakpoint
CREATE VIEW "public"."expense_splits_for_analysis" AS (SELECT es.id AS split_id, es.expense_id, es.user_id, c_user.username AS user_username, (h_user.first_name::text || ' '::text) || h_user.last_name::text AS user_display_name, round(es.amount::numeric / 100.0, 2) AS split_dollars, e.paid_by AS paid_by_user_id, c_payer.username AS payer_username, (h_payer.first_name::text || ' '::text) || h_payer.last_name::text AS payer_display_name, round(es.amount::numeric / 100.0, 2) AS amount_owed_dollars FROM expense_splits es JOIN expenses e ON es.expense_id = e.id LEFT JOIN humans h_user ON es.user_id = h_user.id LEFT JOIN customers c_user ON h_user.id = c_user.human_id LEFT JOIN humans h_payer ON e.paid_by = h_payer.id LEFT JOIN customers c_payer ON h_payer.id = c_payer.human_id ORDER BY es.id DESC);--> statement-breakpoint
CREATE VIEW "public"."expense_summary_for_analysis" AS (SELECT e.id AS expense_id, e.event_id, e.activity_id, e.group_id, round(e.amount::numeric / 100.0, 2) AS amount_dollars, round(e.tip_amount::numeric / 100.0, 2) AS tip_dollars, round((e.amount + e.tip_amount)::numeric / 100.0, 2) AS total_dollars, e.category, e.description, e.paid_by AS payer_id, c_payer.username AS payer_username, (h_payer.first_name::text || ' '::text) || h_payer.last_name::text AS payer_display_name, e.created_at::date AS expense_date, date_part('year'::text, e.created_at) AS expense_year, date_part('month'::text, e.created_at) AS expense_month, date_part('week'::text, e.created_at) AS expense_week, to_char(e.created_at, 'YYYY-MM'::text) AS month_year, e.created_at FROM expenses e LEFT JOIN humans h_payer ON e.paid_by = h_payer.id LEFT JOIN customers c_payer ON h_payer.id = c_payer.human_id ORDER BY e.created_at DESC);--> statement-breakpoint
CREATE VIEW "public"."group_spending_for_analysis" AS (SELECT eg.id AS group_id, eg.name AS group_name, eg.created_at::date AS group_created_date, count(DISTINCT e.id) AS total_expenses, round(sum(e.amount + e.tip_amount)::numeric / 100.0, 2) AS total_group_spending_dollars, round(avg(e.amount + e.tip_amount) / 100.0, 2) AS avg_expense_dollars, min(e.created_at)::date AS first_expense_date, max(e.created_at)::date AS last_expense_date FROM expense_groups eg LEFT JOIN expenses e ON eg.id = e.group_id GROUP BY eg.id, eg.name, eg.created_at ORDER BY (round(sum(e.amount + e.tip_amount)::numeric / 100.0, 2)) DESC);--> statement-breakpoint
CREATE VIEW "public"."user_participant_summary_for_analysis" AS (SELECT h.id AS user_id, c.username, h.first_name, h.last_name, count(DISTINCT es.expense_id) AS expenses_involved_in, round(sum(es.amount)::numeric / 100.0, 2) AS total_owed_dollars, round(avg(es.amount) / 100.0, 2) AS avg_split_dollars FROM humans h LEFT JOIN customers c ON h.id = c.human_id LEFT JOIN expense_splits es ON h.id = es.user_id WHERE es.id IS NOT NULL GROUP BY h.id, c.username, h.first_name, h.last_name ORDER BY (round(sum(es.amount)::numeric / 100.0, 2)) DESC);--> statement-breakpoint
CREATE VIEW "public"."user_payer_summary_for_analysis" AS (SELECT h.id AS user_id, c.username, h.first_name, h.last_name, count(DISTINCT e.id) AS expenses_created, round(sum(e.amount + e.tip_amount)::numeric / 100.0, 2) AS total_paid_dollars, round(avg(e.amount + e.tip_amount) / 100.0, 2) AS avg_expense_dollars, round(sum(e.tip_amount)::numeric / 100.0, 2) AS total_tips_paid_dollars, min(e.created_at)::date AS first_expense_date, max(e.created_at)::date AS last_expense_date FROM humans h LEFT JOIN customers c ON h.id = c.human_id LEFT JOIN expenses e ON h.id = e.paid_by WHERE e.id IS NOT NULL GROUP BY h.id, c.username, h.first_name, h.last_name ORDER BY (round(sum(e.amount + e.tip_amount)::numeric / 100.0, 2)) DESC);